/* Generated by TooT */

package uk.org.toot.swingui.midiui;

import javax.swing.JComboBox;

public class MidiChannelCombo extends JComboBox
{
   	public MidiChannelCombo() {
    	setMaximumRowCount(16); // 16 MIDI channels
//		addItem("n/a");
	    for ( int i = 0 ; i < 16 ; i++ ) {
    	    addItem(new Integer(1+i)) ;
        }
    }
}
