/* Generated by TooT */

package uk.org.toot.swingui.transportui;

import java.net.URL;
import javax.swing.AbstractAction;
import javax.swing.Icon;
import javax.swing.ImageIcon;

abstract public class TransportAction extends AbstractAction
{
    private boolean selected = false;

    public boolean isSelected() { return selected; }

    public void setSelected(boolean newValue) {
        boolean oldValue = this.selected;
        if (oldValue != newValue) {
		    this.selected = newValue;
//                    Log.debug("fire 'selected' "+(String)getValue(Action.NAME)+" "+oldValue+" -> "+newValue);
			firePropertyChange("selected",
//			       		Boolean.valueOf(oldValue), Boolean.valueOf(newValue));
	       		new Boolean(oldValue), new Boolean(newValue));
        }
    }
	public Icon icon(String imageName, String altText) {
        // Look for the image.
		String imgLocation = "/toolbarButtonGraphics/" + imageName // i.e. media/Play24
            + ".gif";
		URL imageURL = this.getClass().getResource(imgLocation);
        if (imageURL != null) { //image found
	    	return new ImageIcon(imageURL);//, altText);
        }
        return null ;
    }
}


